name: Build and commit

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
  
    - name: Commit build
      run:
        git config --global user.name "Giovanni"
        git config --global user.email "giovanni@xproglabs.com"

        git add .
        git commit -m "Build"
        git push --force
