name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: "Deploy Prensa docs to braza-server"
    runs-on: ubuntu-latest
    steps:
      - name: SSH to braza
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          port: 22
          script_stop: true
          script: |
            cd var/www/prensa-designsystem
            git pull
            yarn
            yarn run build-storybook
            pm2 restart 1

      - name: Slack notifcation build success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'build-action'
          text: Deploy da documentação realizado com sucesso.
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack }}
        if: ${{ success() }}
      
      - name: Slack notifcation build error
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'build-action'
          text: Erro ao realizar deploy da documentação.
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack }}
        if: ${{ failure() }}
