name: Publish build and docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.deploy }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: |
        echo "# Config"
        git config --global user.name "Giovanni"
        git config --global user.email "giovanni@xproglabs.com"
        git config pull.ff only
        echo "# Clear changed files"
        git checkout -- .
        echo "# Fetching"
        git fetch --unshallow
        echo "# Pull master"
        git pull
        echo "# Checkout production"
        git checkout production
        echo "# Pull Production"
        git pull
        echo "# Merge master into production"
        git merge master -m "Merge master into production for release"
        echo "# Up version"
        npm version patch
    - run: npm run build
  
    - name: Commit build
      run: |
        git branch
        git add .
        git commit -m "Build"
        git push --force

    - name: Slack notifcation build
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: 'build-action'
        text: Build prensa ${{ job.status }}
        fields: commit, message, author
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.slack }}
      if: ${{ always() }}
