name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: "Deploy Prensa docs to braza-server"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Build storybook
        run: |
          npm install
          npm run build-storybook

      - name: List directories
        run: ls -l

      - uses: actions/checkout@master
      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          port: 22
          rm: true
          source: "./storybookbuild"
          target: "/var/www/prensa-designsystem"
          
      - name: SSH to braza
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          port: 22
          script: |
            pm2 restart 1

      - name: Slack notifcation build success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'build-action'
          text: Deploy da documentação realizado com sucesso.
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack }}
        if: ${{ success() }}
      
      - name: Slack notifcation build error
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'build-action'
          text: Erro ao realizar deploy da documentação.
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack }}
        if: ${{ failure() }}
