name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
    
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/xprog-designsystem/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.2.2
        with:
          source: src/sass/index.scss
          destination: /tmp/xprog-designsystem/css/main.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 1
        
